[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
marketplace = "58G2AW7qke8nEPsL8oVqPMwuetFfR2cbxD1XTZ8XFCcT"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
